#ifndef ELEC2204_INCLUDE_H
#define ELEC2204_INCLUDE_H
    #include <stdlib.h>
    #include <stdio.h>
    #include <iostream>
    #include <fstream>
    #include <sstream>
    #include <vector>
    #include <new>
    #include <iomanip>
    #include <string>
    #include <bitset>
    #include <bits/stdc++.h>
#endif //ELEC2204_INCLUDE_H
